odom_filter_node:
  ros__parameters:
# 1. Set the map_frame, odom_frame, and base_link frames to the appropriate frame names for your system.
#     1a. If your system does not have a map_frame, just remove it, and make sure "world_frame" is set to the value of odom_frame.
# 2. If you are fusing continuous position data such as wheel encoder odometry, visual odometry, or IMU data, set "world_frame"
#    to your odom_frame value. This is the default behavior for robot_localization's state estimation nodes.
# 3. If you are fusing global absolute position data that is subject to discrete jumps (e.g., GPS or position updates from landmark
#    observations) then:
#     3a. Set your "world_frame" to your map_frame value
#     3b. MAKE SURE something else is generating the odom->base_link transform. Note that this can even be another state estimation node
#         from robot_localization! However, that instance should *not* fuse the global data.
    map_frame: track               # Defaults to "map" if unspecified
    odom_frame: odom            # Defaults to "odom" if unspecified
    base_link_frame: base_footprint  # Defaults to "base_link" ifunspecified
    world_frame: track           # Defaults to the value ofodom_frame if unspecified

    odom0: vehicle/wheel_odom
    odom0_config: [false, false, false,  # x, y, z
                  false, false, false,  # roll, pitch, yaw
                  true,  false, false,  # x_dot, y_dot, z_dot
                  false, false, true,  # roll_dot, pitch_dot, yaw_dot
                  false, false, false]  # x_ddot, y_ddot, z_ddot

    imu0: imu/data
    imu0_config: [false, false, false,  # x, y, z
                  false, false, true,  # roll, pitch, yaw
                  false, false, false,  # x_dot, y_dot, z_dot
                  false, false, true,  # roll_dot, pitch_dot, yaw_dot
                  false, false, false]  # x_ddot, y_ddot, z_ddot
    imu0_remove_gravitational_acceleration: true

    odom1: odometry/gps
    odom1_config: [true,  true,  false,
                  false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    odom1_queue_size: 10
    odom1_differential: false
    odom1_relative: false

    frequency: 50.0
    two_d_mode: true
    publish_acceleration: false
    publish_tf: true
    sensor_timeout: 0.1

navsat_transform_node:
  ros__parameters:
    frequency: 30.0
    delay: 0.0
    magnetic_declination_radians: 0.0 # 0.0429351  # For lat/long 55.944831, -3.186998
    yaw_offset: 0.0 # 1.570796327  # IMU reads 0 facing magnetic north, not east
    zero_altitude: false
    broadcast_cartesian_transform: false
    publish_filtered_gps: false
    use_odometry_yaw: false
    wait_for_datum: false
